### ISSUE TITLE
Help With Unity Intergration

### ISSUE THREAD

**Issue by jeffreylanters** [SoPra13/SoPra_Client#3]
Hello! I usually don't do this, but since you're a student I'll make an exception 😋. I've seen your email and am here to help you with your implementation. Let's use this thread to communicate.

**Comment by jeffreylanters** [comment]
I'm looking into it right now. Everything looks fine, but caught my attention is the 'missing function' error. This is not the way javascript should display such an error. I think it is thrown by Unity.

**Comment by jeffreylanters** [comment]
I've googled 'Unity WebGL missing function' and it seems to be an error Unity throws when the external function you're trying to invoke is not present in a jslib file. Are you sure your jslib is included in your final build? Can you show a screenshot of your inspector when selecting the jslib file? You might have the wrong platform settings because you did now create the jslib yourself but copied it over.

**Comment by niddhog** [comment]
Hi Jeffrey!
Wow, thanks a lot for looking into this, this means a lot to me! I've managed to get it to work now, I had to rebuild the WebGl Unity build once more and that did the trick (not sure why exactly).
I wish you all the best and thanks again for your time!
All the best, Chris
